package com.zlebank.zplatform.trade.model;

import com.alibaba.fastjson.annotation.JSONField;

// Generated 2016-8-8 16:38:46 by Hibernate Tools 4.0.0


/**
 * TTxnsWechatOrderinfo generated by hbm2java
 */

public class PojoTxnsWechatOrderinfo implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -7256242183785459987L;
	@JSONField(serialize=false)
	private long tid;
	@JSONField(name="appid")
	private String appid;
	@JSONField(name="mch_id")
	private String mchId;
	@JSONField(name="device_info")
	private String deviceInfo;
	@JSONField(name="body")
	private String body;
	@JSONField(name="detail")
	private String detail;
	@JSONField(name="attach")
	private String attach;
	@JSONField(name="out_trade_no")
	private String outTradeNo;
	@JSONField(name="fee_type")
	private String feeType;
	@JSONField(name="total_fee")
	private Long totalFee;
	@JSONField(name="spbill_create_ip")
	private String spbillCreateIp;
	@JSONField(name="time_start")
	private String timeStart;
	@JSONField(name="time_expire")
	private String timeExpire;
	@JSONField(name="goods_tag")
	private String goodsTag;
	@JSONField(name="notify_url")
	private String notifyUrl;
	@JSONField(name="trade_type")
	private String tradeType;
	@JSONField(name="product_id")
	private String productId;
	@JSONField(name="imit_pay")
	private String imitPay;
	@JSONField(name="openid")
	private String openid;
	@JSONField(serialize=false)
	private String status;
	@JSONField(name="code_url")
	private String codeUrl;
	@JSONField(name="prepay_id")
	private String prepayId;
	@JSONField(serialize=false)
	private String txnseqno;
	/**
	 * @return the tid
	 */
	public long getTid() {
		return tid;
	}
	/**
	 * @param tid the tid to set
	 */
	public void setTid(long tid) {
		this.tid = tid;
	}
	/**
	 * @return the appid
	 */
	public String getAppid() {
		return appid;
	}
	/**
	 * @param appid the appid to set
	 */
	public void setAppid(String appid) {
		this.appid = appid;
	}
	/**
	 * @return the mchId
	 */
	public String getMchId() {
		return mchId;
	}
	/**
	 * @param mchId the mchId to set
	 */
	public void setMchId(String mchId) {
		this.mchId = mchId;
	}
	/**
	 * @return the deviceInfo
	 */
	public String getDeviceInfo() {
		return deviceInfo;
	}
	/**
	 * @param deviceInfo the deviceInfo to set
	 */
	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}
	/**
	 * @return the body
	 */
	public String getBody() {
		return body;
	}
	/**
	 * @param body the body to set
	 */
	public void setBody(String body) {
		this.body = body;
	}
	/**
	 * @return the detail
	 */
	public String getDetail() {
		return detail;
	}
	/**
	 * @param detail the detail to set
	 */
	public void setDetail(String detail) {
		this.detail = detail;
	}
	/**
	 * @return the attach
	 */
	public String getAttach() {
		return attach;
	}
	/**
	 * @param attach the attach to set
	 */
	public void setAttach(String attach) {
		this.attach = attach;
	}
	/**
	 * @return the outTradeNo
	 */
	public String getOutTradeNo() {
		return outTradeNo;
	}
	/**
	 * @param outTradeNo the outTradeNo to set
	 */
	public void setOutTradeNo(String outTradeNo) {
		this.outTradeNo = outTradeNo;
	}
	/**
	 * @return the feeType
	 */
	public String getFeeType() {
		return feeType;
	}
	/**
	 * @param feeType the feeType to set
	 */
	public void setFeeType(String feeType) {
		this.feeType = feeType;
	}
	/**
	 * @return the totalFee
	 */
	public Long getTotalFee() {
		return totalFee;
	}
	/**
	 * @param totalFee the totalFee to set
	 */
	public void setTotalFee(Long totalFee) {
		this.totalFee = totalFee;
	}
	/**
	 * @return the spbillCreateIp
	 */
	public String getSpbillCreateIp() {
		return spbillCreateIp;
	}
	/**
	 * @param spbillCreateIp the spbillCreateIp to set
	 */
	public void setSpbillCreateIp(String spbillCreateIp) {
		this.spbillCreateIp = spbillCreateIp;
	}
	/**
	 * @return the timeStart
	 */
	public String getTimeStart() {
		return timeStart;
	}
	/**
	 * @param timeStart the timeStart to set
	 */
	public void setTimeStart(String timeStart) {
		this.timeStart = timeStart;
	}
	/**
	 * @return the timeExpire
	 */
	public String getTimeExpire() {
		return timeExpire;
	}
	/**
	 * @param timeExpire the timeExpire to set
	 */
	public void setTimeExpire(String timeExpire) {
		this.timeExpire = timeExpire;
	}
	/**
	 * @return the goodsTag
	 */
	public String getGoodsTag() {
		return goodsTag;
	}
	/**
	 * @param goodsTag the goodsTag to set
	 */
	public void setGoodsTag(String goodsTag) {
		this.goodsTag = goodsTag;
	}
	/**
	 * @return the notifyUrl
	 */
	public String getNotifyUrl() {
		return notifyUrl;
	}
	/**
	 * @param notifyUrl the notifyUrl to set
	 */
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}
	/**
	 * @return the tradeType
	 */
	public String getTradeType() {
		return tradeType;
	}
	/**
	 * @param tradeType the tradeType to set
	 */
	public void setTradeType(String tradeType) {
		this.tradeType = tradeType;
	}
	/**
	 * @return the productId
	 */
	public String getProductId() {
		return productId;
	}
	/**
	 * @param productId the productId to set
	 */
	public void setProductId(String productId) {
		this.productId = productId;
	}
	/**
	 * @return the imitPay
	 */
	public String getImitPay() {
		return imitPay;
	}
	/**
	 * @param imitPay the imitPay to set
	 */
	public void setImitPay(String imitPay) {
		this.imitPay = imitPay;
	}
	/**
	 * @return the openid
	 */
	public String getOpenid() {
		return openid;
	}
	/**
	 * @param openid the openid to set
	 */
	public void setOpenid(String openid) {
		this.openid = openid;
	}
	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}
	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}
	/**
	 * @return the codeUrl
	 */
	public String getCodeUrl() {
		return codeUrl;
	}
	/**
	 * @param codeUrl the codeUrl to set
	 */
	public void setCodeUrl(String codeUrl) {
		this.codeUrl = codeUrl;
	}
	/**
	 * @return the prepayId
	 */
	public String getPrepayId() {
		return prepayId;
	}
	/**
	 * @param prepayId the prepayId to set
	 */
	public void setPrepayId(String prepayId) {
		this.prepayId = prepayId;
	}
	/**
	 * @return the txnseqno
	 */
	public String getTxnseqno() {
		return txnseqno;
	}
	/**
	 * @param txnseqno the txnseqno to set
	 */
	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}

	
	
}
