package com.zlebank.zplatform.trade.model;
// default package
// Generated 2016-3-14 18:23:59 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TTxnsInsteadPay generated by hbm2java
 */

public class PojoTxnsInsteadPay implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -4867441730131379452L;
	private long tid;
	private String insteadPayNo;
	private String channelCode;
	private String transferType;
	private String reqFile;
	private String resFile;
	private Date startDate;
	private Date endDate;
	private String status;
	private String remarks;

	public PojoTxnsInsteadPay() {
	}

	/**
	 * @return the tid
	 */
	public long getTid() {
		return tid;
	}

	/**
	 * @param tid the tid to set
	 */
	public void setTid(long tid) {
		this.tid = tid;
	}

	/**
	 * @return the insteadPayNo
	 */
	public String getInsteadPayNo() {
		return insteadPayNo;
	}

	/**
	 * @param insteadPayNo the insteadPayNo to set
	 */
	public void setInsteadPayNo(String insteadPayNo) {
		this.insteadPayNo = insteadPayNo;
	}

	/**
	 * @return the channelCode
	 */
	public String getChannelCode() {
		return channelCode;
	}

	/**
	 * @param channelCode the channelCode to set
	 */
	public void setChannelCode(String channelCode) {
		this.channelCode = channelCode;
	}

	/**
	 * @return the transferType
	 */
	public String getTransferType() {
		return transferType;
	}

	/**
	 * @param transferType the transferType to set
	 */
	public void setTransferType(String transferType) {
		this.transferType = transferType;
	}

	/**
	 * @return the reqFile
	 */
	public String getReqFile() {
		return reqFile;
	}

	/**
	 * @param reqFile the reqFile to set
	 */
	public void setReqFile(String reqFile) {
		this.reqFile = reqFile;
	}

	/**
	 * @return the resFile
	 */
	public String getResFile() {
		return resFile;
	}

	/**
	 * @param resFile the resFile to set
	 */
	public void setResFile(String resFile) {
		this.resFile = resFile;
	}

	/**
	 * @return the startDate
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * @param startDate the startDate to set
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * @return the endDate
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * @param endDate the endDate to set
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * @return the remarks
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	
	

	

}
