package com.zlebank.zplatform.trade.model;
// default package
// Generated 2015-12-15 13:55:09 by Hibernate Tools 4.0.0


/**
 * TTxnsSms generated by hbm2java
 */

public class TxnsSmsModel implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = -6007806950155205472L;
    private long tid;
    private String tn;
    private String mobile;
    private String verifycode;
    private String content;
    private String sendtime;
    private String overduetime;
    private String busicode;
    private String busitype;
    private String retcode;
    private String retinfo;
	/**
	 * @return the tid
	 */
	public long getTid() {
		return tid;
	}
	/**
	 * @param tid the tid to set
	 */
	public void setTid(long tid) {
		this.tid = tid;
	}
	/**
	 * @return the tn
	 */
	public String getTn() {
		return tn;
	}
	/**
	 * @param tn the tn to set
	 */
	public void setTn(String tn) {
		this.tn = tn;
	}
	/**
	 * @return the mobile
	 */
	public String getMobile() {
		return mobile;
	}
	/**
	 * @param mobile the mobile to set
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}
	/**
	 * @return the verifycode
	 */
	public String getVerifycode() {
		return verifycode;
	}
	/**
	 * @param verifycode the verifycode to set
	 */
	public void setVerifycode(String verifycode) {
		this.verifycode = verifycode;
	}
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
	/**
	 * @return the sendtime
	 */
	public String getSendtime() {
		return sendtime;
	}
	/**
	 * @param sendtime the sendtime to set
	 */
	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}
	/**
	 * @return the overduetime
	 */
	public String getOverduetime() {
		return overduetime;
	}
	/**
	 * @param overduetime the overduetime to set
	 */
	public void setOverduetime(String overduetime) {
		this.overduetime = overduetime;
	}
	/**
	 * @return the busicode
	 */
	public String getBusicode() {
		return busicode;
	}
	/**
	 * @param busicode the busicode to set
	 */
	public void setBusicode(String busicode) {
		this.busicode = busicode;
	}
	/**
	 * @return the busitype
	 */
	public String getBusitype() {
		return busitype;
	}
	/**
	 * @param busitype the busitype to set
	 */
	public void setBusitype(String busitype) {
		this.busitype = busitype;
	}
	/**
	 * @return the retcode
	 */
	public String getRetcode() {
		return retcode;
	}
	/**
	 * @param retcode the retcode to set
	 */
	public void setRetcode(String retcode) {
		this.retcode = retcode;
	}
	/**
	 * @return the retinfo
	 */
	public String getRetinfo() {
		return retinfo;
	}
	/**
	 * @param retinfo the retinfo to set
	 */
	public void setRetinfo(String retinfo) {
		this.retinfo = retinfo;
	}

   
}
