package com.zlebank.zplatform.trade.model;
// Generated 2015-11-9 9:45:58 by Hibernate Tools 4.0.0


/**
 * TTxnsNotifyTask generated by hbm2java
 */

public class TxnsNotifyTaskModel implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 1112312515568183790L;
    private long id;
    private String memberId;
    private String txnseqno;
    private Integer sendTimes;
    private Integer maxSendTimes;
    private String data;
    private String sendStatus;
    private String httpRescode;
    private String notifyUrl;
    private String taskType;
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}
	/**
	 * @return the memberId
	 */
	public String getMemberId() {
		return memberId;
	}
	/**
	 * @param memberId the memberId to set
	 */
	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}
	/**
	 * @return the txnseqno
	 */
	public String getTxnseqno() {
		return txnseqno;
	}
	/**
	 * @param txnseqno the txnseqno to set
	 */
	public void setTxnseqno(String txnseqno) {
		this.txnseqno = txnseqno;
	}
	/**
	 * @return the sendTimes
	 */
	public Integer getSendTimes() {
		return sendTimes;
	}
	/**
	 * @param sendTimes the sendTimes to set
	 */
	public void setSendTimes(Integer sendTimes) {
		this.sendTimes = sendTimes;
	}
	/**
	 * @return the maxSendTimes
	 */
	public Integer getMaxSendTimes() {
		return maxSendTimes;
	}
	/**
	 * @param maxSendTimes the maxSendTimes to set
	 */
	public void setMaxSendTimes(Integer maxSendTimes) {
		this.maxSendTimes = maxSendTimes;
	}
	/**
	 * @return the data
	 */
	public String getData() {
		return data;
	}
	/**
	 * @param data the data to set
	 */
	public void setData(String data) {
		this.data = data;
	}
	/**
	 * @return the sendStatus
	 */
	public String getSendStatus() {
		return sendStatus;
	}
	/**
	 * @param sendStatus the sendStatus to set
	 */
	public void setSendStatus(String sendStatus) {
		this.sendStatus = sendStatus;
	}
	/**
	 * @return the httpRescode
	 */
	public String getHttpRescode() {
		return httpRescode;
	}
	/**
	 * @param httpRescode the httpRescode to set
	 */
	public void setHttpRescode(String httpRescode) {
		this.httpRescode = httpRescode;
	}
	/**
	 * @return the notifyUrl
	 */
	public String getNotifyUrl() {
		return notifyUrl;
	}
	/**
	 * @param notifyUrl the notifyUrl to set
	 */
	public void setNotifyUrl(String notifyUrl) {
		this.notifyUrl = notifyUrl;
	}
	/**
	 * @return the taskType
	 */
	public String getTaskType() {
		return taskType;
	}
	/**
	 * @param taskType the taskType to set
	 */
	public void setTaskType(String taskType) {
		this.taskType = taskType;
	}
    
}
