package com.zlebank.zplatform.trade.model;

import java.util.Date;

/**
 * TTxnsWithdraw generated by hbm2java
 */

public class TxnsWithdrawModel implements java.io.Serializable {

    /**
     * serialVersionUID
     */
    private static final long serialVersionUID = -5624809894940365318L;
    private long id;
    private String withdraworderno;
    private String batchno;
    private String memberid;
    private String withdrawtype;
    private Long amount;
    private String acctno;
    private String acctname;
    private String bankcode;
    private String bankname;
    private Long fee;
    private String txntime;
    private String finishtime;
    private String status;
    private String withdrawinstid;
    private String retcode;
    private String retinfo;
    private Long inuser;
    private Date intime;
    private Long stexauser;
    private Date stexatime;
    private String stexaopt;
    private Long cvlexauser;
    private Date cvlexatime;
    private String cvlexaopt;
    private String notes;
    private String remarks;
    private String gatewayorderno;
    private String texnseqno;
	/**
	 * @return the id
	 */
	public long getId() {
		return id;
	}
	/**
	 * @param id the id to set
	 */
	public void setId(long id) {
		this.id = id;
	}
	/**
	 * @return the withdraworderno
	 */
	public String getWithdraworderno() {
		return withdraworderno;
	}
	/**
	 * @param withdraworderno the withdraworderno to set
	 */
	public void setWithdraworderno(String withdraworderno) {
		this.withdraworderno = withdraworderno;
	}
	/**
	 * @return the batchno
	 */
	public String getBatchno() {
		return batchno;
	}
	/**
	 * @param batchno the batchno to set
	 */
	public void setBatchno(String batchno) {
		this.batchno = batchno;
	}
	/**
	 * @return the memberid
	 */
	public String getMemberid() {
		return memberid;
	}
	/**
	 * @param memberid the memberid to set
	 */
	public void setMemberid(String memberid) {
		this.memberid = memberid;
	}
	/**
	 * @return the withdrawtype
	 */
	public String getWithdrawtype() {
		return withdrawtype;
	}
	/**
	 * @param withdrawtype the withdrawtype to set
	 */
	public void setWithdrawtype(String withdrawtype) {
		this.withdrawtype = withdrawtype;
	}
	/**
	 * @return the amount
	 */
	public Long getAmount() {
		return amount;
	}
	/**
	 * @param amount the amount to set
	 */
	public void setAmount(Long amount) {
		this.amount = amount;
	}
	/**
	 * @return the acctno
	 */
	public String getAcctno() {
		return acctno;
	}
	/**
	 * @param acctno the acctno to set
	 */
	public void setAcctno(String acctno) {
		this.acctno = acctno;
	}
	/**
	 * @return the acctname
	 */
	public String getAcctname() {
		return acctname;
	}
	/**
	 * @param acctname the acctname to set
	 */
	public void setAcctname(String acctname) {
		this.acctname = acctname;
	}
	/**
	 * @return the bankcode
	 */
	public String getBankcode() {
		return bankcode;
	}
	/**
	 * @param bankcode the bankcode to set
	 */
	public void setBankcode(String bankcode) {
		this.bankcode = bankcode;
	}
	/**
	 * @return the bankname
	 */
	public String getBankname() {
		return bankname;
	}
	/**
	 * @param bankname the bankname to set
	 */
	public void setBankname(String bankname) {
		this.bankname = bankname;
	}
	/**
	 * @return the fee
	 */
	public Long getFee() {
		return fee;
	}
	/**
	 * @param fee the fee to set
	 */
	public void setFee(Long fee) {
		this.fee = fee;
	}
	/**
	 * @return the txntime
	 */
	public String getTxntime() {
		return txntime;
	}
	/**
	 * @param txntime the txntime to set
	 */
	public void setTxntime(String txntime) {
		this.txntime = txntime;
	}
	/**
	 * @return the finishtime
	 */
	public String getFinishtime() {
		return finishtime;
	}
	/**
	 * @param finishtime the finishtime to set
	 */
	public void setFinishtime(String finishtime) {
		this.finishtime = finishtime;
	}
	/**
	 * @return the status
	 */
	public String getStatus() {
		return status;
	}
	/**
	 * @param status the status to set
	 */
	public void setStatus(String status) {
		this.status = status;
	}
	/**
	 * @return the withdrawinstid
	 */
	public String getWithdrawinstid() {
		return withdrawinstid;
	}
	/**
	 * @param withdrawinstid the withdrawinstid to set
	 */
	public void setWithdrawinstid(String withdrawinstid) {
		this.withdrawinstid = withdrawinstid;
	}
	/**
	 * @return the retcode
	 */
	public String getRetcode() {
		return retcode;
	}
	/**
	 * @param retcode the retcode to set
	 */
	public void setRetcode(String retcode) {
		this.retcode = retcode;
	}
	/**
	 * @return the retinfo
	 */
	public String getRetinfo() {
		return retinfo;
	}
	/**
	 * @param retinfo the retinfo to set
	 */
	public void setRetinfo(String retinfo) {
		this.retinfo = retinfo;
	}
	/**
	 * @return the inuser
	 */
	public Long getInuser() {
		return inuser;
	}
	/**
	 * @param inuser the inuser to set
	 */
	public void setInuser(Long inuser) {
		this.inuser = inuser;
	}
	/**
	 * @return the intime
	 */
	public Date getIntime() {
		return intime;
	}
	/**
	 * @param intime the intime to set
	 */
	public void setIntime(Date intime) {
		this.intime = intime;
	}
	/**
	 * @return the stexauser
	 */
	public Long getStexauser() {
		return stexauser;
	}
	/**
	 * @param stexauser the stexauser to set
	 */
	public void setStexauser(Long stexauser) {
		this.stexauser = stexauser;
	}
	/**
	 * @return the stexatime
	 */
	public Date getStexatime() {
		return stexatime;
	}
	/**
	 * @param stexatime the stexatime to set
	 */
	public void setStexatime(Date stexatime) {
		this.stexatime = stexatime;
	}
	/**
	 * @return the stexaopt
	 */
	public String getStexaopt() {
		return stexaopt;
	}
	/**
	 * @param stexaopt the stexaopt to set
	 */
	public void setStexaopt(String stexaopt) {
		this.stexaopt = stexaopt;
	}
	/**
	 * @return the cvlexauser
	 */
	public Long getCvlexauser() {
		return cvlexauser;
	}
	/**
	 * @param cvlexauser the cvlexauser to set
	 */
	public void setCvlexauser(Long cvlexauser) {
		this.cvlexauser = cvlexauser;
	}
	/**
	 * @return the cvlexatime
	 */
	public Date getCvlexatime() {
		return cvlexatime;
	}
	/**
	 * @param cvlexatime the cvlexatime to set
	 */
	public void setCvlexatime(Date cvlexatime) {
		this.cvlexatime = cvlexatime;
	}
	/**
	 * @return the cvlexaopt
	 */
	public String getCvlexaopt() {
		return cvlexaopt;
	}
	/**
	 * @param cvlexaopt the cvlexaopt to set
	 */
	public void setCvlexaopt(String cvlexaopt) {
		this.cvlexaopt = cvlexaopt;
	}
	/**
	 * @return the notes
	 */
	public String getNotes() {
		return notes;
	}
	/**
	 * @param notes the notes to set
	 */
	public void setNotes(String notes) {
		this.notes = notes;
	}
	/**
	 * @return the remarks
	 */
	public String getRemarks() {
		return remarks;
	}
	/**
	 * @param remarks the remarks to set
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	/**
	 * @return the gatewayorderno
	 */
	public String getGatewayorderno() {
		return gatewayorderno;
	}
	/**
	 * @param gatewayorderno the gatewayorderno to set
	 */
	public void setGatewayorderno(String gatewayorderno) {
		this.gatewayorderno = gatewayorderno;
	}
	/**
	 * @return the texnseqno
	 */
	public String getTexnseqno() {
		return texnseqno;
	}
	/**
	 * @param texnseqno the texnseqno to set
	 */
	public void setTexnseqno(String texnseqno) {
		this.texnseqno = texnseqno;
	}
    
    
}
